---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: endurosat-cicd
  labels:
    app: endurosat-cicd
spec:
  selector:
    matchLabels:
      app: endurosat-cicd
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: endurosat-cicd
    spec:
      containers:
        - name: endurosat-cicd
          image: gitlab.devops.davar.com:2053/root/endurosat-cicd:latest
      imagePullSecrets:
        - name: registry-credentials
      restartPolicy: Always
